config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :categories
  resource :home, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :articles do
    resources :comments, only: [:create, :destroy]
    member do
      get 'like', to: 'articles#like'
      get 'unlike', to: 'articles#unlike'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  default_scope { order(created_at: :desc) }
  belongs_to :author, class_name: 'User'
  has_many :article_categories, inverse_of: :article, dependent: :destroy
  has_many :categories, through: :article_categories, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :categories, allow_destroy: true, reject_if: :all_blank

  mount_uploader :image, ImageUploader
  is_impressionable
  acts_as_votable

  validates_presence_of :title, :text, :image
  validates_presence_of :categories
  validates :title, length: { maximum: 70 }
  validates :text, length: { maximum: 800 }
  validates :title, :text, uniqueness: true
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories, inverse_of: :category, dependent: :destroy
  has_many :articles, through: :article_categories, dependent: :destroy

  scope :ordered_by_priority, -> { order(priority: :desc) }

  validates_presence_of :name, :priority
  validates :name, length: { maximum: 15 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all.ordered_by_priority
  end

  def show
    @category = Category.ordered_by_priority.includes(:articles).find(params[:id])
    @articles = @category.articles
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def change_style(article, ind = 0)
    ind -= 1 if ind.odd?
    if (ind % 4).zero?
      render partial: 'partials/category/style1', locals: { article: article }
    else
      render partial: 'partials/category/style2', locals: { article: article }
    end
  end
end

app/views/partials/category/_new_category.html.erb
<label class="label">Create New Category</label>
<div class="control ">
  <span class="category">
    <%= foo.simple_fields_for :categories, @article.categories.build do |fields| %>
      <%= fields.input :name %>
      <%= fields.input :priority %>
    <% end %>
  </span>
</div>

app/views/partials/category/_present_category.html.erb
<div class="field">
  <label class="label">Category</label>
  <div class="control">
    <span class="checkbox">
      <%= foo.collection_check_boxes :category_ids, 
                                    Category.all,
                                    :id,
                                    :name,
                                    label_html: { class: 'label checkbox' }
      %>
    </span>
  </div>
</div>

app/views/partials/category/_style1.html.erb
<div class="article-wrapper">
  <div class="cat-art-img">
    <div class="art-image">
      <%= image_tag article.image_url(:thumbnail), alt: article.title %>
    </div>
  </div>

  <div class="art-text">
    <h6 class="art-head is-5"><%= @category.name %></h6>
    <h5 class="art-title">
      <%= link_to article_path(article) do %>
        <%= article.title %>
      <% end %>
    </h5>
    <p class=""><%= truncate(article.text, length: 100) %></p>
    <div class="author-corner">
      <h5 class="author-name"><%= article.author.name %></h5>
      <small class="author-title">Author</small>
    </div>
    <nav class="level">
      <div class="level-left"></div>
      <div class="level-right">
        <div class="level-item views data">
          <%= link_to article, class: 'link' do %>
            <span class="icon"><i class="fa fa-eye"></i></span>
            <%= article.impressionist_count %>
          <% end %>
        </div>
        <div class="level-item comments data">
          <%= link_to article, class: 'link' do %>
            <span class="icon"><i class="fa fa-comment"></i></span>
            <%= article.comments.count %>
          <% end %>
        </div>
        <div class="level-item likes">
          <%= like_unlike(article)%>
        </div>
      </div>
    </nav>
  </div>

</div>

app/views/partials/category/_style2.html.erb
<div class="article-wrapper">
  <div class="art-text">
    <h6 class="art-head is-5"><%= @category.name %></h6>
    <h5 class="art-title">
      <%= link_to article_path(article) do %>
        <%= article.title %>
      <% end %>
    </h5>
    <p class=""><%= truncate(article.text, length: 100) %></p>
    <div class="author-corner">
      <h5 class="author-name"><%= article.author.name %></h5>
      <small class="author-title">Author</small>
    </div>
    <nav class="level">
      <div class="level-left"></div>
        <div class="level-right">
        <div class="level-item views data">
          <%= link_to article, class: 'link' do %>
            <span class="icon"><i class="fa fa-eye"></i></span>
            <%= article.impressionist_count %>
          <% end %>
        </div>
        <div class="level-item comments data">
          <%= link_to article, class: 'link' do %>
            <span class="icon"><i class="fa fa-comment"></i></span>
            <%= article.comments.count %>
          <% end %>
        </div>
        <div class="level-item likes">
          <%= like_unlike(article) %>
        </div>
      </div>
    </nav>
  </div>

  <div class="cat-art-img">
    <div class="art-image">
      <%= image_tag article.image_url(:thumbnail), alt: article.title %>
    </div>
  </div>
</div>