config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :categories
  resource :home, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :articles do
    resources :comments, only: [:create, :destroy]
    member do
      get 'like', to: 'articles#like'
      get 'unlike', to: 'articles#unlike'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  default_scope { order(created_at: :desc) }
  belongs_to :author, class_name: 'User'
  has_many :article_categories, inverse_of: :article, dependent: :destroy
  has_many :categories, through: :article_categories, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :categories, allow_destroy: true, reject_if: :all_blank

  mount_uploader :image, ImageUploader
  is_impressionable
  acts_as_votable

  validates_presence_of :title, :text, :image
  validates_presence_of :categories
  validates :title, length: { maximum: 70 }
  validates :text, length: { maximum: 800 }
  validates :title, :text, uniqueness: true
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy like unlike]
  impressionist action: [:show], unique: %i[impressionable_type impressionable_id session_hash]

  def index
    @articles = Article.includes(:comments)
    @featured_article = Article.unscoped.order(cached_votes_up: :desc).limit(1)
    @article = @featured_article.last
  end

  def show
    @article = Article.includes(:comments).find(params[:id])
    @comments = @article.comments
  end

  def new
    @article = current_user.articles.build
    @categories = Category.ordered_by_priority
  end

  def edit; end

  def create
    @article = current_user.articles.build(article_params)
    @categories = Category.ordered_by_priority

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @article = Article.find(params[:id])
    @article.liked_by current_user

    respond_to do |format|
      format.html { redirect_back fallback_location: category_path }
    end
  end

  def unlike
    @article = Article.find(params[:id])
    @article.unliked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: category_path }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :image, category_ids: [], categories_attributes: %i[name priority])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  # article_show
  def comments_form
    if logged_in?
      render partial: 'comments/form'
    else
      render partial: 'partials/articles/comment_signup'
    end
  end

  def present_category(cat, foo)
    render partial: 'partials/category/present_category', locals: { foo: foo } if cat.present?
  end

  def hide_form(cat, foo)
    class_name = cat.size == 5 ? 'field dnone' : 'field'
    content_tag(:div, class: class_name) do
      render partial: 'partials/category/new_category', locals: { foo: foo }
    end
  end

  # article index
  def like_unlike(article)
    if logged_in?
      if current_user.liked?(article)
        render partial: 'partials/articles/unlike_article', locals: { article: article }
      else
        render partial: 'partials/articles/like_article', locals: { article: article }
      end
    else
      render partial: 'partials/articles/like_article', locals: { article: article }
    end
  end
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |foo| %>
  <%= foo.error_notification %>

  <%= foo.error_notification message: foo.object.errors[:base].to_sentence if foo.object.errors[:base].present? %>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

  <div class="form-inputs">
    <div class="field">
      <div class="control">
        <%= foo.input :title,
                    required: true,
                    autofocus: true,
                    input_html: { class: 'input' },
                    wrapper: false,
                    label_html: { class: 'label' }
        %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= foo.input :image,
                    as: :file,
                    required: true,
                    wrapper: false,
                    label_html: { class: 'label' }
        %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= foo.input :text,
                    required: true,
                    input_html: { class: 'textarea' },
                    wrapper: false,
                    label_html: { class: 'label' }
        %>
      </div>
    </div>

    <%= present_category(@categories, foo) %>
    
    <%= hide_form(@categories, foo) %>

  </div>

  <div class="form-actions">
    <%= foo.button :submit, class: "button is-info" %>
  </div>
<% end %>
<br />

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="section">
  <p id="notice"><%= notice %></p>

  <h1 class='title'>Articles</h1>
  <div class="article">
    <% @articles.each do |article| %>
      <div class="level-left article-box">
        <article class="media">
          <figure class="media-left">
            <p class="image">
              <%= cl_image_tag article.image_url(:thumbnail), alt: article.title %>
            <nav class="level">
              <div class="level-right has-background-black df">
                <div class="level-item views data">
                  <%= link_to article do %>
                    <span class="icon"><i class="fa fa-eye"></i></span>
                    <%= article.impressionist_count %>
                  <% end %>
                </div>
                <div class="level-item comments data">
                  <%= link_to article do %>
                    <span class="icon"><i class="fa fa-comment"></i></span>
                    <%= article.comments.count %>
                  <% end %>
                </div>
                <div class="level-item likes">
                  <%= like_unlike(article) %>
                </div>
              </div>
            </nav>
            </p>
          </figure>
          <div class="media-content text">
            <div class="content">
              <h5 class="art-title">
                <%= link_to article_path(article) do %>
                  <%= article.title %>
                <% end %>
              </h5>
              <p>
                <%= truncate(article.text, length: 120) %>
              </p>
            </div>
            <div class="author-corner">
              <h5 class="author-name"><%= article.author.name %></h5>
              <small class="author-title">Author</small>
            </div>
          </div>
        </article>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="columns is-centered">
  <div class="column is-half">
    <div class="new-art-wrapper">
      <h1 class="title is-5">New Article</h1>

      <%= render 'form', article: @article %>

      <%= link_to 'Back', articles_path %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="columns is-centered hcisch">
  <div class="column is-8">
    <h1 class="title is-2 has-text-grey article-title"><%= @article.title %></h1>
    <h3 class="subtitle is-5 has-text-grey-lighter"> by <%= @article.author.username %></h3>
    <div class="level">
      <div class="level-left"></div>
      <div class="level-right">
        <% if article_path(@article) %>
          <div class="buttons">
            <%= link_to 'Edit article', edit_article_path(@article), class:'button'%>
            <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Delete article?" }, class:'button' %>
          </div>
        <% end %>
      </div>
    </div>
    <figure class="image">
      <%= cl_image_tag @article.image_url(:main), alt: @article.title%>
    </figure>
    <div class="content"><%= @article.text %></div>
    
    <section>
      <div class="container">
        <h2 class="subtitle is-5"><%= pluralize(@article.comments.count, 'comment')%></h2>
        <%= render @article.comments %>
      </div>

      <h3 class="subtitle is-3 has-text-grey">Leave a comment</h3>
      <%= comments_form %>
    </section>
  </div>


</div>